repos:
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        args: [--config, pyproject.toml]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--config, .ruff.toml, --fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--config-file, pyproject.toml]
        additional_dependencies: [mypy==1.10.0, types-PyYAML, types-pydantic]
  - repo: https://github.com/pytest-dev/pytest
    rev: 8.3.3
    hooks:
      - id: pytest
        args: [--config, pytest.ini, -m, "not qt"]
        additional_dependencies: [pytest==7.4.0, pytest-qt==4.4.0, PySide6==6.7.0, PyYAML==6.0.0, pydantic==2.0.0]
        stages: [commit]
      - id: pytest
        args: [--config, pytest.ini, -m, qt]
        additional_dependencies: [pytest==7.4.0, pytest-qt==4.4.0, PySide6==6.7.0, PyYAML==6.0.0, pydantic==2.0.0]
        stages: [commit]